### ISSUE TITLE
player.rank is undefined

### ISSUE THREAD

**Issue by KoNoLinLie** [hypixelts/hypixel.ts#230]

**Comment by KoNoLinLie** [comment]
I use it for my query bot
![QQ截图20240404180552](https://github.com/hypixelts/hypixel.ts/assets/101704410/e8571cc3-3f74-40a8-81a8-2ccd7e743c37)
this is the code
![QQ图片20240404180626](https://github.com/hypixelts/hypixel.ts/assets/101704410/46f2c038-b657-4ce3-bf2c-0fad931af2f8)
player.rank should be mvp_plus but it returns undefined

**Comment by FC5570** [comment]
Hello @KoNoLinLie.

As per [Hypixel API Documentation](https://api.hypixel.net/#tag/Player-Data/paths/~1v2~1player/get), rank is not the player's actual rank, but the role (Admin, Moderator, Helper, Normal). This field might not be necessarily present.

Try using [`Player.packageRank`](https://hypixel.js.org/docs/documentation/classes/Player#packagerank), or [`Player.newPackageRank`](https://hypixel.js.org/docs/documentation/classes/Player#newpackagerank). I just tried with your username and `newPackageRank` is `MVP_PLUS`.
