### ISSUE TITLE
Return Friends as expected rather than having to implicitly cast them

### ISSUE THREAD

**Issue by chriscn** [hypixelts/hypixel.ts#8]
### Issue description

https://github.com/hypixelts/hypixel.ts/blob/3890323571ca8be3a99c013b067476edddf0357c/src/managers/PlayerManager.ts#L56

This should return an interface of Friend that has the correct values.

```ts
interface Friend {
    _id: string;
    started: number;
    uuidReceiver: string;
    uuidSender: string;
}
```

You have to cast to unknown and then cast back.

### Code sample

```typescript
const rawResponse = await hpclient.players.getFriends(args[0]);

let friends = rawResponse as unknown as Friend[];

interface Friend {
    _id: string;
    started: number;
    uuidReceiver: string;
    uuidSender: string;
}
```

### Package version

1.1.0

### Node.js version

v17.8.0

### Operating system

macOS

### Priority this issue should have

Low (slightly annoying)

**Comment by FC5570** [comment]
Fixed in #16
