### ISSUE TITLE
Unable to access Guild Manager

### ISSUE THREAD

**Issue by chriscn** [hypixelts/hypixel.ts#9]
### Issue description

![](https://cdn.discordapp.com/attachments/931507129481830400/958042894726496266/Screenshot_2022-03-28_at_17.40.23.png)

### Package version

v1.1.0

### Node.js version

v17.8.0

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

**Comment by FC5570** [comment]
Fixed in #16
